//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by jwpce.rc
//
#define IDS_ABOUT_TEXT                  1
#define IDS_ABOUT_TITLE                 2
#define IDS_ERROR_TERMINAL              3
#define IDS_FP_FORMATFILE               4
#define IDS_FP_INVALIDTEXT              5
#define IDS_FP_INVALIDTITLE             6
#define IDS_ERROR                       7
#define IDS_WARNING                     8
#define IDS_ERROR_MEMORY                9
#define IDS_AREYOUSURE                  10
#define IDS_CK_TEXT                     11
#define IDS_CK_TITLE                    12
#define IDS_CK_ERROR                    13
#define IDS_SR_NOSEARCH                 14
#define IDS_SR_NOTFOUND                 15
#define IDS_LIST_IMPORT                 16
#define IDS_LIST_IMPORTERROR            17
#define IDS_LIST_POPUP                  18
#define IDS_CE_ERRORTEXT                19
#define IDS_CE_ERRORTITLE               20
#define IDS_CE_ERROREMPTY               21
#define IDS_CE_ERRORKANA                22
#define IDS_CE_ERRORGODAN               23
#define IDS_CE_ERRORVERB                24
#define IDS_CE_FILETYPE                 25
#define IDS_CE_ERROROPEN                26
#define IDS_ERROR_SAVECONVERT           27
#define IDS_ERROR_CLIPTEXT              28
#define IDS_ERROR_CLIPTITLE             29
#define IDS_STAT_OVR                    30
#define IDS_STAT_INS                    31
#define IDS_STAT_ASCII                  32
#define IDS_STAT_KANJI                  33
#define IDS_STAT_JASCII                 34
#define IDS_STAT_HALFKANA               35
#define IDS_STAT_UNTYPED                36
#define IDS_STAT_TYPEASCII              37
#define IDS_STAT_TYPEJWPCE              38
#define IDS_STAT_TYPEJWP                39
#define IDS_STAT_TYPEEUC                40
#define IDS_STAT_TYPESJIS               41
#define IDS_STAT_TYPENEW                42
#define IDS_STAT_TYPEOLD                43
#define IDS_STAT_TYPENEC                44
#define IDS_STAT_TYPEUNICODE            45
#define IDS_STAT_TYPEUTF7               46
#define IDS_STAT_TYPEUTF8               47
#define IDS_STAT_TYPEJFC                48
#define IDS_STAT_TYPE1                  49
#define IDS_KI_TYPEUNKNOWN              50
#define IDS_KI_TYPEASCII                51
#define IDS_KI_TYPEEXTENDED             52
#define IDS_KI_TYPESYMBOL               53
#define IDS_KI_TYPEJASCII               54
#define IDS_KI_TYPEHIRAGANA             55
#define IDS_KI_TYPEKATAKANA             56
#define IDS_KI_TYPEGREEK                57
#define IDS_KI_TYPERUSSIAN              58
#define IDS_KI_TYPERESERVED             59
#define IDS_KI_TYPEKANJI1               60
#define IDS_KI_TYPEKANJI2               61
#define IDS_KI_SKIPPOSITION             62
#define IDS_KI_SKIPSTROKE               63
#define IDS_KI_SKIPBOTH                 64
#define IDS_KI_SKIPBREEN                65
#define IDS_KI_ERRORTITLE               66
#define IDS_KI_ERROROPEN                67
#define IDS_KI_ERRORVERSION             68
#define IDS_CK_SUMMARYTITLE             69
#define IDS_CK_SUMMARY                  70
#define IDS_DICT_BEGIN                  71
#define IDS_DICT_END                    72
#define IDS_DICT_PERSONALNAMES          73
#define IDS_DICT_PLACENAMES             74
#define IDS_DICT_VULGAR                 75
#define IDS_DICT_X                      76
#define IDS_DICT_COLLOQUIAL             77
#define IDS_DICT_MANGA                  78
#define IDS_DICT_SLANG                  79
#define IDS_DICT_MARIAL                 80
#define IDS_DICT_IDIOMATIC              81
#define IDS_DICT_ARCHAIC                82
#define IDS_DICT_OBSOLETE               83
#define IDS_DICT_OBSCURE                84
#define IDS_DICT_KANA                   85
#define IDS_DICT_ABBREVIATION           86
#define IDS_DICT_POLITE                 87
#define IDS_DICT_HUMBLE                 88
#define IDS_DICT_FAMILIAR               89
#define IDS_DICT_HONORIFIC              90
#define IDS_DICT_FEMALE                 91
#define IDS_DICT_MALE                   92
#define IDS_DICT_PREFIX                 93
#define IDS_DICT_SUFFIX                 94
#define IDS_DICT_KANJI                  95
#define IDS_DE_ERROR                    96
#define IDS_DE_ERRORKANA                97
#define IDS_DE_ERRORNONKANA             98
#define IDS_DE_ERRORMEANING             99
#define IDS_DE_FILETYPE                 100
#define IDS_DE_ERROROPEN                101
#define IDS_DS_SEARCH                   102
#define IDS_DS_BYPASS                   103
#define IDS_DS_INDEX                    104
#define IDS_DS_NAME                     105
#define IDS_DS_NAMEONLY                 106
#define IDS_DS_ERROR                    107
#define IDS_DS_ERRORNOTDICT             108
#define IDS_DS_ALREADYTEXT              109
#define IDS_DS_ALREADYTITLE             110
#define IDS_DS_ERROROPEN                111
#define IDS_DD_CLASSICAL                112
#define IDS_DD_CANNOTOPEN               113
#define IDS_DD_MATCHREJECT              114
#define IDS_DD_MATCH                    115
#define IDS_DD_DICTINDEX                116
#define IDS_DD_SEARCHING                117
#define IDS_DD_ERRORLENGTH              118
#define IDS_DD_ERRORASCIIKANA           119
#define IDS_DD_ABORTREJECT              120
#define IDS_DD_ABORT                    121
#define IDS_DD_NOMATCH                  122
#define IDS_DS_FILETYPE                 123
#define IDS_DS_ERROREMPTY               124
#define IDS_DS_DOESNOTEXIST             125
#define IDS_RL_NONE                     126
#define IDS_RL_TOOMANY                  127
#define IDS_IL_NELSON                   128
#define IDS_IL_HAIG                     129
#define IDM_MAINMENU                    130
#define IDS_IL_HALPERN                  130
#define IDM_POPUP                       131
#define IDS_IL_GRADE                    131
#define IDS_IL_MOROHASHILONG            132
#define IDS_IL_MOROHASHISHORT           133
#define IDS_IL_SPAHN                    134
#define IDS_IL_HENSHALL                 135
#define IDS_IL_GAKKEN                   136
#define IDS_IL_HEISIG                   137
#define IDS_IL_ONEILL                   138
#define IDS_IL_FREQUENCY                139
#define IDA_MAINACCEL                   140
#define IDS_IL_RESERVED                 140
#define IDS_IL_DEROO                    140
#define IDS_RL_ERRORRADINDEX            141
#define IDS_RL_ERROR                    142
#define IDS_RL_ERRORTEXT                143
#define IDS_RL_ERRORSTRINDEX            144
#define IDS_RL_ON                       145
#define IDS_RL_KUN                      146
#define IDS_RL_ONKUN                    147
#define IDS_RL_MEANING                  148
#define IDS_RL_NANORI                   149
#define IDS_RL_PINYIN                   150
#define IDB_CURSOR                      151
#define IDS_RL_KOREAN                   151
#define IDB_RADICALS                    152
#define IDS_RL_ERRORKANA                152
#define IDB_STROKES                     153
#define IDS_RL_ERRORKANAFOUND           153
#define IDB_SKIPTYPES                   154
#define IDS_RL_ERRORNONKANA             154
#define IDB_FCSHAPES                    155
#define IDS_FILE_UNNAMED                155
#define IDS_FILE_CORRUPTED              156
#define IDS_FILE_ERROR                  157
#define IDS_FILE_LAST                   158
#define IDS_FILE_CREATEFATAL            159
#define IDI_MAINICON                    160
#define IDS_FILE_DELETETITLE            160
#define IDI_FILEICON                    161
#define IDS_FILE_DELETETEXT             161
#define IDI_ALTICON                     162
#define IDS_FILE_PROJTITLE              162
#define IDI_ICON1                       163
#define IDS_FILE_PROJTEXT               163
#define IDB_BITMAP1                     164
#define IDS_FILE_PROJERROR              164
#define IDS_FILE_PROJCORRUP             165
#define IDS_FILE_PROJSAVE               166
#define IDS_FILE_ERRORJWPCE             167
#define IDS_FILE_REVERT                 168
#define IDS_FILE_ERRORTEMP              169
#define IDS_FILE_ERRORWRITE             170
#define IDS_FILE_OVERWRITE              171
#define IDS_FILE_FILTERSGENERAL         172
#define IDS_FILE_FILTERSOPEN            173
#define IDS_INST_GROUP                  174
#define IDS_INST_FILETYPE               175
#define IDS_START_CONFIGLOAD            176
#define IDS_START_CONFIGSAVE            177
#define IDS_START_CONFIGWRITE           178
#define IDS_OC_AUTO                     179
#define IDD_ADVINSTALL                  180
#define IDS_OC_EUC                      180
#define IDD_CONVERTEDIT                 181
#define IDS_OC_SHIFTJIS                 181
#define IDD_DICTIONARIES                182
#define IDS_OC_NEWJIS                   182
#define IDD_DICTIONARY                  183
#define IDS_OC_OLDJIS                   183
#define IDD_DICTOPTIONS                 184
#define IDS_OC_NECJIS                   184
#define IDD_DUPLICATE                   185
#define IDS_OC_UNICODE                  185
#define IDD_DICTUSEREDIT                186
#define IDS_OC_UTF7                     186
#define IDD_DICTEDITDICTIONARIES        187
#define IDS_OC_UTF8                     187
#define IDD_FILES                       188
#define IDS_TERM_MENU                   188
#define IDD_FORMATPARA                  189
#define IDS_TERM_POPUP                  189
#define IDD_REPLACECONFIRM              190
#define IDS_TERM_ACCEL                  190
#define IDD_SAVECHECK                   191
#define IDS_TERM_REGCLASS               191
#define IDD_INSTALL                     192
#define IDS_TERM_WINDOW                 192
#define IDD_JISTABLE                    193
#define IDS_TERM_INITIALIZE             193
#define IDD_KANJICOUNT                  194
#define IDS_TERM_FONTS                  194
#define IDD_KANJIINFO                   195
#define IDS_TERM_STATUS                 195
#define IDD_PRINTING                    196
#define IDS_TERM_KANAKANJI              196
#define IDD_RADICALLOOKUP               197
#define IDS_TERM_CONTROLS               197
#define IDD_REPLACE                     198
#define IDS_TERM_FILEWINDOW             198
#define IDD_DICTUSER                    199
#define IDS_TERM_INFO                   199
#define IDD_SEARCH                      200
#define IDS_TERM_LOOKUP                 200
#define IDD_CONVERTUSER                 201
#define IDS_TERM_STARTUP                201
#define IDD_LAYOUTADVANCED              202
#define IDS_OPTS_GENERAL                202
#define IDD_LAYOUTDATE                  203
#define IDS_OPTS_DISPLAY                203
#define IDD_LAYOUTHEADER                204
#define IDS_OPTS_FONT                   204
#define IDD_LAYOUTMARGINS               205
#define IDS_OPTS_FILECLIP               205
#define IDD_LAYOUTSUMMARY               206
#define IDS_OPTS_MISC                   206
#define IDD_OPTIONS                     207
#define IDS_OPTS_ADVANCED               207
#define IDD_OPTADVANCED                 208
#define IDS_TOOL_NEW                    208
#define IDD_OPTDISPLAY                  209
#define IDS_TOOL_OPEN                   209
#define IDD_OPTFILE                     210
#define IDS_TOOL_SAVE                   210
#define IDD_OPTFONT                     211
#define IDS_CE_ERRORVERB2               211
#define IDD_OPTGENERAL                  212
#define IDS_TOOL_DELETE                 212
#define IDD_OPTMISC                     213
#define IDS_TOOL_PRINT                  213
#define IDD_CHOOSECOLOR                 214
#define IDS_TOOL_UNDO                   214
#define IDD_LAYOUT                      215
#define IDS_TOOL_REDO                   215
#define IDD_OPTIONS1                    216
#define IDS_TOOL_KANJI                  216
#define IDD_MOREINFO                    217
#define IDS_TOOL_ASCII                  217
#define IDD_SKIPLOOKUP                  218
#define IDS_TOOL_JASCII                 218
#define IDD_FCLOOKUP                    219
#define IDS_TOOL_CUT                    219
#define IDD_BUSHULOOKUP                 220
#define IDS_TOOL_COPY                   220
#define IDD_KANJIVIEW                   221
#define IDS_TOOL_PASTE                  221
#define IDD_INDEXLOOKUP                 222
#define IDS_TOOL_SEARCH                 222
#define IDD_XREFINFO                    223
#define IDS_TOOL_REPLACE                223
#define IDD_READINGLOOKUP               224
#define IDS_TOOL_NEXT                   224
#define IDD_HSLOOKUP                    225
#define IDB_HSRADICALS                  225
#define IDS_TOOL_REVERSE                225
#define IDD_BUSHU2LOOKUP                226
#define IDB_RADLOOKUP                   226
#define IDS_TOOL_CONVERT                226
#define IDB_BUSHULOOKUP                 227
#define IDS_TOOL_INFO                   227
#define IDB_DICTIONARY                  228
#define IDS_TOOL_RADICAL                228
#define IDB_KANJICONVERT                229
#define IDS_TOOL_BUSHU                  229
#define IDB_CHARINFO                    230
#define IDS_TOOL_BS                     230
#define IDS_TOOL_SKIP                   231
#define IDS_TOOL_HS                     232
#define IDB_RIGHTLEFT                   233
#define IDS_TOOL_FOURCORNER             233
#define IDB_RIGHTLEFT1                  234
#define IDS_TOOL_READING                234
#define IDB_TOOLBAR                     235
#define IDS_TOOL_INDEX                  235
#define IDS_TOOL_JISTABLE               236
#define IDS_TOOL_COUNTKANJI             237
#define IDS_TOOL_COLORKANJI             238
#define IDB_HPCTOOLS                    239
#define IDS_TOOL_FORMATFILE             239
#define IDB_PPCTOOLS                    240
#define IDS_TOOL_FORMATPARA             240
#define IDS_TOOL_LAYOUT                 241
#define IDS_TOOL_DICTIONARY             242
#define IDS_TOOL_CONVERSIONS            243
#define IDS_TOOL_OPTIONS                244
#define IDS_LH_HEADODD                  245
#define IDS_LH_HEADEVEN                 246
#define IDS_LH_FOOTODD                  247
#define IDS_LH_FOOTEVEN                 248
#define IDS_LH_HEADER                   249
#define IDS_LH_FOOTER                   250
#define IDS_LM_CM                       251
#define IDS_LM_INCH                     252
#define IDS_LAYOUT_MARGINS              253
#define IDS_LAYOUT_HEADFOOT             254
#define IDS_LAYOUT_SUMMARY              255
#define IDS_LAYOUT_DATETIME             256
#define IDS_LAYOUT_ADVANCED             257
#define IDS_PRINT_ERROR                 258
#define IDS_PRINT_NOPRINTERS            259
#define IDS_PRINT_ABORT                 260
#define IDS_PRINT_PAGE                  261
#define IDS_PRINT_ERRORTEXT             262
#define IDS_TOOL_TIPS                   263
#define IDS_DU_CHANGEDTEXT              264
#define IDS_DU_CLOSE                    265
#define IDS_CE_CHANGEDTEXT              266
#define IDS_CE_CLOSE                    267
#define IDS_LANG_ID                     268
#define IDS_LANG_ERRORTEXT              269
#define IDS_LANG_ERRORTITLE             270
#define IDS_CE_ERRORRUVERB              271
#define IDS_CE_ERRORIADJ                272
#define IDS_MI_NELSON                   273
#define IDS_MI_HALPERN                  274
#define IDS_MI_ONEILL                   275
#define IDS_MI_JIS0208                  276
#define IDS_MI_JIS0212                  277
#define IDS_MI_SKIP                     278
#define IDS_MI_DEROO                    279
#define IDC_CKALL                       1000
#define IDC_CKEXCLUDE                   1001
#define IDC_CKINCLUDE                   1002
#define IDC_CKFREQUENCY                 1003
#define IDC_CKONYOMI                    1004
#define IDC_CKKUNYOMI                   1005
#define IDC_CKMEANING                   1006
#define IDC_CKNUMBER                    1007
#define IDC_CKINFO                      1008
#define IDC_CKINSERT                    1009
#define IDC_CKLIST                      1010
#define IDC_AIJCE                       1020
#define IDC_AIJWP                       1021
#define IDC_AIEUC                       1022
#define IDC_AISJS                       1023
#define IDC_AIJIS                       1024
#define IDC_AIOLD                       1025
#define IDC_AINEC                       1026
#define IDC_AIUTF                       1027
#define IDC_AIJCP                       1028
#define IDC_AISTART                     1029
#define IDC_AIDESKTOP                   1030
#define IDC_IDADVANCED                  1030
#define IDC_AIGROUP                     1031
#define IDC_IDINSTALL                   1031
#define IDC_TABHELP                     1033
#define IDC_CEKANA                      1040
#define IDC_CEKANJI                     1041
#define IDC_CEGODAN                     1042
#define IDC_CEICHIDAN                   1043
#define IDC_CEIADJ                      1044
#define IDC_DEKANA                      1050
#define IDC_DEKANJI                     1051
#define IDC_DEMEANING                   1052
#define IDC_DSENABLE                    1060
#define IDC_DSNAMES                     1061
#define IDC_DSINDEX                     1062
#define IDC_DSONLY                      1063
#define IDC_DSDESCRIPTION               1064
#define IDC_DSFILE                      1065
#define IDC_DSBROWSE                    1066
#define IDC_DCEDICT                     1070
#define IDC_DCNAMDICT                   1071
#define IDC_DCUSERDICT                  1072
#define IDC_DCQUIET                     1073
#define IDC_DCTOGGLE                    1074
#define IDC_DDSTRING                    1080
#define IDC_DDRESULT                    1081
#define IDC_DDBEGIN                     1082
#define IDC_DDEND                       1083
#define IDC_DDNONAME                    1084
#define IDC_DDNOPLACE                   1085
#define IDC_DDADVANCED                  1085
#define IDC_DDUSER                      1086
#define IDC_DDOPTIONS                   1087
#define IDC_DDINSERT                    1088
#define IDC_DDSTATUS                    1089
#define IDC_DOEXCLUDE                   1100
#define IDC_DOCOMPRESS                  1101
#define IDC_DOAUTO                      1102
#define IDC_DODICTIONARIES              1103
#define IDC_DOUSERDICT                  1104
#define IDC_DOADVSEARCH                 1105
#define IDC_DOADVI                      1106
#define IDC_DOADVALWAYS                 1107
#define IDC_DOADVALL                    1108
#define IDC_DOCLIPBOARD                 1109
#define IDC_DOCLASSICAL                 1110
#define IDC_TABCONTROL                  1111
#define IDC_DFOPEN                      1115
#define IDC_DFREPLACE                   1116
#define IDC_SCSAVE                      1120
#define IDC_SCNO                        1120
#define IDC_FDFILES                     1130
#define IDC_FPLEFT                      1140
#define IDC_FPRIGHT                     1141
#define IDC_FPFIRST                     1142
#define IDC_FPSPACING                   1143
#define IDC_KILIST                      1150
#define IDC_KIFROMCLIP                  1151
#define IDC_KIINSERT                    1152
#define IDC_KIBIGKANJI                  1153
#define IDC_KIMORE                      1154
#define IDC_KITYPE                      1155
#define IDC_KIXREF                      1155
#define IDC_KIJISCODE                   1156
#define IDC_KISHIFTJIS                  1157
#define IDC_KIUNICODE                   1158
#define IDC_KISTROKES                   1159
#define IDC_KIBUSHU                     1160
#define IDC_KIBUSHUCHAR                 1161
#define IDC_KICLASSICALCHAR             1162
#define IDC_KIGRADE                     1163
#define IDC_KINELSON                    1164
#define IDC_KIHAIG                      1165
#define IDC_KIHALPERN                   1166
#define IDC_KISKIP                      1167
#define IDC_KISHDICT                    1168
#define IDC_KISHKANA                    1169
#define IDC_KIFC                        1170
#define IDC_KIFC2                       1171
#define IDC_KIMDLONG                    1172
#define IDC_KIMDSHORT                   1173
#define IDC_KIPINYIN                    1174
#define IDC_KIKOREAN                    1175
#define IDC_RLRADICALS                  1180
#define IDC_RLCLEAR                     1181
#define IDC_RLINFO                      1182
#define IDC_RLINSERT                    1183
#define IDC_RLANY                       1184
#define IDC_RLPM2                       1185
#define IDC_RLPM1                       1186
#define IDC_RLAUTO                      1187
#define IDC_RLRESULT                    1188
#define IDC_RLMESSAGE                   1189
#define IDC_RLSTROKE                    1190
#define IDC_RLSPIN                      1191
#define IDC_RLCOPY                      1192
#define IDC_RLCOPYKANJI                 1193
#define IDC_JTJISCODE                   1210
#define IDC_JTEUCCODE                   1211
#define IDC_JTSJISCODE                  1212
#define IDC_JTUNICODE                   1213
#define IDC_JTINFO                      1214
#define IDC_JTINSERT                    1215
#define IDC_JTTABLE                     1216
#define IDC_JTCLIP                      1217
#define IDC_LAPOSHEADLEFT               1220
#define IDC_LAPOSHEADRIGHT              1221
#define IDC_LAPOSHEADTOP                1222
#define IDC_LAPOSHEADBOTTOM             1223
#define IDC_LAJUSTIFY                   1224
#define IDC_LDDATE                      1230
#define IDC_LDTIME                      1231
#define IDC_LDAM                        1232
#define IDC_LDPM                        1233
#define IDC_LHNOFIRST                   1240
#define IDC_LHODDEVEN                   1241
#define IDC_LHEDIT                      1242
#define IDC_LHHEADLEFT                  1250
#define IDC_LHHEADCENTER                1251
#define IDC_LHHEADRIGHT                 1252
#define IDC_LHCODES                     1253
#define IDC_LMFLEFT                     1260
#define IDC_LMFRIGHT                    1261
#define IDC_LMFTOP                      1262
#define IDC_LMFBOTTOM                   1263
#define IDC_LMFVERTICAL                 1264
#define IDC_LMFLANDSCAPE                1265
#define IDC_LMFROMDEFAULT               1266
#define IDC_LMFUNITS                    1267
#define IDC_LMFWIDTH                    1268
#define IDC_LMDLEFT                     1270
#define IDC_LMDRIGHT                    1271
#define IDC_LMDTOP                      1272
#define IDC_LMDBOTTOM                   1273
#define IDC_LMDVERTICAL                 1274
#define IDC_LMDLANDSCAPE                1275
#define IDC_LMFROMFILE                  1276
#define IDC_LMDUNITS                    1277
#define IDC_LMDWIDTH                    1278
#define IDC_LSTITLE                     1290
#define IDC_LSSUBJECT                   1291
#define IDC_LSAUTHOR                    1292
#define IDC_LSKEYWORDS                  1293
#define IDC_LSCOMMENTS                  1294
#define IDC_PSNAME                      1300
#define IDC_PSMESSAGE                   1301
#define IDC_OGRESTOREPOS                1310
#define IDC_OGRELOADFILES               1311
#define IDC_OGSAVESETTINGS              1312
#define IDC_OGCONFIRMEXIT               1313
#define IDC_OGWIDTHDYNAMIC              1314
#define IDC_OGWIDTHFIXED                1315
#define IDC_OGWIDTHPRINTER              1316
#define IDC_OGCLOSEFILE                 1317
#define IDC_OGCLOSEPROGRAM              1318
#define IDC_OGWIDTH                     1319
#define IDC_OGINCHES                    1321
#define IDC_OGCM                        1322
#define IDC_ODVSCROLL                   1330
#define IDC_ODHSCROLL                   1331
#define IDC_ODKSCROLL                   1332
#define IDC_ODSTATUSBAR                 1333
#define IDC_ODKBARTOP                   1334
#define IDC_ODSTATUSABOVE               1335
#define IDC_ODHIGHLIGHT                 1336
#define IDC_ODHIGHLIGHTBOX              1337
#define IDC_ODTOOLBAR                   1338
#define IDC_OFASCIIFONT                 1350
#define IDC_OFDISPLAYFONT               1351
#define IDC_OFPRINTFONT                 1352
#define IDC_OFRELAXPUNCT                1353
#define IDC_OFRELAXSMALL                1354
#define IDC_OFAUTOFONT                  1355
#define IDC_OFPRINTSIZE                 1356
#define IDC_OFASCIINAME                 1357
#define IDC_OFHEIGHT                    1358
#define IDC_OFALL                       1359
#define IDC_OFSHOWALL                   1359
#define IDC_OCSAVEBACKUP                1370
#define IDC_OCCLIPIMPORT                1371
#define IDC_OCCLIPEXPORT                1372
#define IDC_OCDUPOPEN                   1373
#define IDC_OCDUPCHANGE                 1374
#define IDC_OCDUPPROMPT                 1375
#define IDC_OCNOBITMAP                  1376
#define IDC_OCNOUNICODE                 1377
#define IDC_OMINFOTITLES                1390
#define IDC_OMRADSELINFO                1391
#define IDC_OMRADSELINSERT              1392
#define IDC_OMCOLORKANJI                1393
#define IDC_OMINLIST                    1394
#define IDC_OMNOTINLIST                 1395
#define IDC_OMKANJICOLOR                1396
#define IDC_OMCOLORBITMAP               1397
#define IDC_OMCOLORPRINT                1398
#define IDC_OMINSERTLINE                1399
#define IDC_OMKANJIBOX                  1400
#define IDC_OMINFOCOMPRESS              1401
#define IDC_OAALLOCSIZE                 1410
#define IDC_OACONVERTSIZE               1411
#define IDC_OAUNDOLEVELS                1412
#define IDC_OAFONTCACHE                 1414
#define IDC_OACACHEDISPLAY              1415
#define IDC_OAINFO                      1416
#define IDC_OACACHEINFO                 1416
#define IDC_SRSEARCH                    1430
#define IDC_SRREPLACE                   1431
#define IDC_SRCASE                      1432
#define IDC_SRJASCII                    1433
#define IDC_SRBACKWARD                  1434
#define IDC_SRWRAP                      1435
#define IDC_SRALLFILES                  1436
#define IDC_SRNOCONFIRM                 1437
#define IDC_EDITMODE2                   1438
#define IDC_RCNOREP                     1450
#define IDC_RCALL                       1451
#define IDC_CCSAMPLE                    1470
#define IDC_CCRED                       1471
#define IDC_CCREDSPIN                   1472
#define IDC_CCGREEN                     1473
#define IDC_CCGREENSPIN                 1474
#define IDC_CCBLUE                      1475
#define IDC_CCBLUESPIN                  1476
#define IDC_CCBOX1                      1477
#define IDC_CCBOX2                      1478
#define IDC_CCBOX3                      1479
#define IDC_CCBOX4                      1480
#define IDC_CCBOX5                      1481
#define IDC_CCBOX6                      1482
#define IDC_CCBOX7                      1483
#define IDC_CCBOX8                      1484
#define IDC_CCBOX9                      1485
#define IDC_CCBOX10                     1486
#define IDC_CCBOX11                     1487
#define IDC_CCBOX12                     1488
#define IDC_CCBOX13                     1489
#define IDC_CCBOX14                     1490
#define IDC_CCBOX15                     1491
#define IDC_CCBOX16                     1492
#define IDC_CCBOX17                     1493
#define IDC_CCBOX18                     1494
#define IDC_CCBOX19                     1495
#define IDC_CCBOX20                     1496
#define IDC_CCBOX21                     1497
#define IDC_CCBOX22                     1498
#define IDC_CCBOX23                     1499
#define IDC_CCBOX24                     1500
#define IDC_MIFREQ                      1510
#define IDC_MIHENSHALL                  1511
#define IDC_MIGAKKEN                    1512
#define IDC_MIHEISIG                    1513
#define IDC_MIONEILL                    1514
#define IDC_MIXREF                      1515
#define IDC_MINEXT                      1516
#define IDC_MIINSERT                    1517
#define IDC_SLTYPE                      1520
#define IDC_SLTYPESPIN                  1521
#define IDC_SLS1                        1522
#define IDC_SLS1SPIN                    1523
#define IDC_SLS2                        1524
#define IDC_SLS2SPIN                    1525
#define IDC_SLMISSCODES                 1526
#define IDC_SLSKIPTYPE                  1527
#define IDC_FC1                         1540
#define IDC_FC1SPIN                     1541
#define IDC_FC2                         1542
#define IDC_FC2SPIN                     1543
#define IDC_FC3                         1544
#define IDC_FC3SPIN                     1545
#define IDC_FC4                         1546
#define IDC_FC4SPIN                     1547
#define IDC_FC5                         1548
#define IDC_FC5SPIN                     1549
#define IDC_FCSHAPES                    1550
#define IDC_BLNELSON                    1560
#define IDC_BLCLASSICAL                 1561
#define IDC_BLSTROKE                    1562
#define IDC_BLSPIN                      1563
#define IDC_ILTYPE                      1580
#define IDC_ILINDEX                     1581
#define IDC_ILVOL                       1582
#define IDC_RLTYPE                      1600
#define IDC_RLKUN                       1601
#define IDC_RLSTRING                    1602
#define IDC_RLWORD                      1603
#define IDC_HSRADSTROKE                 1620
#define IDC_HSRADSRKSPIN                1621
#define IDC_HSRADICAL                   1622
#define IDC_HSRADSPIN                   1623
#define IDC_HSOTHER                     1624
#define IDC_HSOTHERSPIN                 1625
#define IDC_HSKANJI                     1626
#define IDC_HSKANJISPIN                 1627
#define IDC_HSVARIANTS                  1628
#define IDC_HSRADCHAR                   1629
#define IDC_EDITLIST                    2000
#define IDC_EDITLISTADD                 2001
#define IDC_EDITLISTEDIT                2002
#define IDC_EDITLISTDELETE              2003
#define IDC_EDITLISTUP                  2004
#define IDC_EDITLISTDOWN                2005
#define IDC_EDITLISTIMPORT              2006
#define IDC_EDITLISTINSERT              2007
#define IDC_EDITMODE                    2100
#define IDC_DATA                        2200
#define IDM_FILE_NEW                    10001
#define IDM_FILE_OPEN                   10002
#define IDM_FILE_REVERT                 10003
#define IDM_FILE_CLOSE                  10004
#define IDM_FILE_CLOSEALL               10005
#define IDM_FILE_SAVE                   10006
#define IDM_FILE_SAVEALL                10007
#define IDM_FILE_SAVEAS                 10008
#define IDM_FILE_PRINT                  10009
#define IDM_FILE_PRINTERSETUP           10010
#define IDM_FILE_EXIT                   10011
#define IDM_FILE_FILES_NONE             10012
#define IDM_EDIT_UNDO                   10013
#define IDM_EDIT_REDO                   10014
#define IDM_EDIT_CUT                    10015
#define IDM_EDIT_COPY                   10016
#define IDM_EDIT_PASTE                  10017
#define IDM_EDIT_SELECTALL              10018
#define IDM_EDIT_INSERTPAGEBREAK        10019
#define IDM_EDIT_SEARCH                 10020
#define IDM_EDIT_REPLACE                10021
#define IDM_EDIT_FINDNEXT               10022
#define IDM_EDIT_REVERSESEARCH          10023
#define IDM_EDIT_MODE_KANJI             10024
#define IDM_EDIT_MODE_ASCII             10025
#define IDM_EDIT_MODE_JASCII            10026
#define IDM_KANJI_CONVERT               10027
#define IDM_KANJI_RADICALLOOKUP         10028
#define IDM_KANJI_GETINFO               10029
#define IDM_KANJI_JISTABLE              10030
#define IDM_KANJI_COUNTKANJI            10031
#define IDM_KANJI_MAKEKANJILIST         10032
#define IDM_KANJI_CLEARKANJILIST        10033
#define IDM_UTILITIES_FORMATFILE        10034
#define IDM_UTILITIES_FORMATPARAGRAPH   10035
#define IDM_UTILITIES_PAGELAYOUT        10036
#define IDM_UTILITIES_DICTIONARY        10037
#define IDM_UTILITIES_VOCABLIST         10038
#define IDM_UTILITIES_USERCONVERSION    10039
#define IDM_UTILITIES_OPTIONS           10040
#define IDM_UTILITIES_DEFAULTOPTIONS    10041
#define IDM_UTILITIES_SAVESETTINGS      10042
#define IDM_UTILITIES_INSTALL           10043
#define IDM_WINDOW_NEXTFILE             10044
#define IDM_WINDOW_PREVIOUSFILE         10045
#define IDM_WINDOW_FILES                10046
#define IDM_HELP_MAININDEX              10047
#define IDM_HELP_ABOUTJWPCE             10048
#define IDM_FILE_FILES_BASE             20000
#define IDM_WINDOW_FILES_BASE           21000
#define IDM_LIST_GETINFO                30001
#define IDM_LIST_REPLACETOFILE          30002
#define IDM_LIST_COPY                   30003
#define IDM_LIST_INSERTTOFILE           30004
#define IDM_LIST_INSERTTONEWFILE        30005
#define IDM_LIST_INSERTTOANYFILE        30006
#define IDM_LIST_INSERTTO               30007
#define IDM_EDIT_MODE_TOGGLE            40056
#define ID_FILE_DELETE                  40057
#define IDM_FILE_DELETE                 40058
#define IDM_KANJI_SKIPLOOKUP            40059
#define IDM_KANJI_FCLOOKUP              40060
#define IDM_KANJI_BUSHULOOKUP           40061
#define IDM_KANJI_READINGLOOKUP         40062
#define IDM_KANJI_INDEXLOOKUP           40063
#define IDM_KANJI_HSLOOKUP              40064
#define IDM_KANJI_BUSHU2LOOKUP          40065
#define IDM_UTILITIES_TOGGLE            40066
#define IDM_UTILITIES_CUSTOMIZE         40067

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        241
#define _APS_NEXT_COMMAND_VALUE         40068
#define _APS_NEXT_CONTROL_VALUE         2236
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
