# SPDX-License-Identifier: GPL-2.0-or-later
find_program(DESKTOP_VALIDATE desktop-file-validate REQUIRED)
find_program(MIME_UPDATE update-mime-database REQUIRED)
find_program(CPACK cpack REQUIRED)
string(RANDOM LENGTH 10 ALPHABET abcdef0123456789 suffix)
set(root "${BUILD}/tests/delivery-${suffix}")
file(MAKE_DIRECTORY "${root}/installed" "${root}/unpacked")
function(run)
  execute_process(COMMAND ${ARGV} WORKING_DIRECTORY "${root}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 90)
  if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Delivery command failed: ${ARGV}\n${output}\n${errors}")
  endif()
endfunction()
run("${CMAKE_COMMAND}" --install "${BUILD}" --prefix "${root}/installed")
foreach(path bin/jwpqt share/applications/jwpqt.desktop share/icons/hicolor/scalable/apps/jwpqt.svg
             share/mime/packages/jwpqt-mime.xml share/doc/jwpqt/handbook/start.md
             share/doc/jwpqt/handbook/gnugpl.txt share/doc/jwpqt/handbook/_cpright.txt)
  if(NOT EXISTS "${root}/installed/${path}")
    message(FATAL_ERROR "Missing installed file: ${path}")
  endif()
endforeach()
file(READ "${root}/installed/share/icons/hicolor/scalable/apps/jwpqt.svg" icon_contents)
if(NOT icon_contents MATCHES "<svg[^>]*viewBox=\"0 0 64 64\"")
  message(FATAL_ERROR "Installed application icon is not the scalable SVG artwork")
endif()
run("${DESKTOP_VALIDATE}" "${root}/installed/share/applications/jwpqt.desktop")
run("${MIME_UPDATE}" "${root}/installed/share/mime")
file(READ "${root}/installed/share/mime/packages/jwpqt-mime.xml" mime_definition)
foreach(required "*.jce" "*.jwp" "\\147\\046\\002\\102")
  string(FIND "${mime_definition}" "${required}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "Installed JWP MIME definition is missing ${required}")
  endif()
endforeach()
run("${CMAKE_COMMAND}" -E env QT_QPA_PLATFORM=offscreen
    "${root}/installed/bin/jwpqt" --resource-report
    --config-dir "${root}/config" --user-data-dir "${root}/data")
if(EXISTS "${root}/config/query-history.bin" OR EXISTS "${root}/config/jwpqt.cfg")
  message(FATAL_ERROR "Installed resource report wrote user state")
endif()
run("${CMAKE_COMMAND}" -E env QT_QPA_PLATFORM=offscreen
    "${root}/installed/bin/jwpqt" --handbook --smoke-test
    --config-dir "${root}/config" --user-data-dir "${root}/data")
run("${CPACK}" --config "${BUILD}/CPackConfig.cmake" -G TGZ -B "${root}/packages")
file(GLOB archives "${root}/packages/*.tar.gz")
list(LENGTH archives count)
if(NOT count EQUAL 1)
  message(FATAL_ERROR "Expected one native archive")
endif()
list(GET archives 0 archive)
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar tf "${archive}" OUTPUT_VARIABLE listing RESULT_VARIABLE result)
if(NOT result STREQUAL "0" OR listing MATCHES "(wnn\\.dat|wnn\\.dix|kanjinfo\\.dat|enamdict|edict\\.jdx|/\\.serena/|/\\.git/)")
  message(FATAL_ERROR "Archive failed inspection or includes non-deliverable resources: ${listing}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar xzf "${archive}"
                WORKING_DIRECTORY "${root}/unpacked" RESULT_VARIABLE result)
if(NOT result STREQUAL "0")
  message(FATAL_ERROR "Archive extraction failed")
endif()
file(GLOB packaged "${root}/unpacked/*/bin/jwpqt")
list(LENGTH packaged count)
if(NOT count EQUAL 1)
  message(FATAL_ERROR "Archive layout is not relocatable")
endif()
list(GET packaged 0 binary)
run("${CMAKE_COMMAND}" -E env QT_QPA_PLATFORM=offscreen
    "${binary}" --handbook --smoke-test --config-dir "${root}/config" --user-data-dir "${root}/data")
run("${CPACK}" --config "${BUILD}/CPackSourceConfig.cmake" -G TGZ -B "${root}/source")
file(GLOB sources "${root}/source/*.tar.gz")
list(LENGTH sources count)
if(NOT count EQUAL 1)
  message(FATAL_ERROR "Expected one corresponding-source archive")
endif()
list(GET sources 0 source)
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar tf "${source}"
                OUTPUT_VARIABLE listing RESULT_VARIABLE result)
if(NOT result STREQUAL "0" OR listing MATCHES "/[.](git|serena)/")
  message(FATAL_ERROR "Source archive failed inspection or includes private metadata")
endif()
foreach(required "/CMakeLists.txt" "/src/qt/help_window.cpp" "/src/core/jwp_document.cpp"
                 "/docs/handbook/start.md" "/gnugpl.txt" "/_cpright.txt")
  string(FIND "${listing}" "${required}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "Corresponding source archive is missing ${required}")
  endif()
endforeach()
message(STATUS "Installed and packaged help, corresponding source, licenses, desktop/MIME and data boundary passed")
file(REMOVE_RECURSE "${root}")
